library(MASS)
library(xtable)
library()
data<-read.csv('data/simple_amazon_for_R.csv')
data<-filter(data, Rating > -1)
r0 <- polr(as.factor(Rating) ~ Action * Actor, data = data, method = "probit")
r1 <- polr(as.factor(Rating) ~ Action, data = data, method = "probit")
c<-anova(r0,r1)
xtable(c)